### PR TITLE
When a photo is deleted or moved on the file system, the coresponding…

### PR DESCRIPTION
**Pull request by stz184**
… cache folder and database record are deleted.

### CODE REVIEW

**Comment by stz184** [comment]
This is my first go code, so please be nice :) 
I am open to constructive critics all the time.

**Comment by viktorstrate** [comment]
Thank you so much, i will take a proper look tomorow

**Comment by stz184** [comment]
> Thank you so much, i will take a proper look tomorow

Is there any issue with the PR? I am open to suggestions.

**Comment by viktorstrate** [comment]
I have had some problems installing the latest mariadb on my macbook pro, which have made it hard to test. It looks great though!

Would you mind moving the [`deleteOldUserAlbums` function](https://github.com/viktorstrate/photoview/blob/master/api/scanner/scanner_user.go#L160) to `cleanup_media.go`?
Just for better structure 😊

Otherwise it looks great! I will try to test it in docker on my dekstop computer tomorrow if I have time for it. (I'm not currently at home)

**Comment by stz184** [comment]
Hey, excuse me for the delayed reply :( I was able to do the refactoring, I just haven't enough time yesterday :(
Thank you that did it instead of me!

**Comment by viktorstrate** [comment]
No worries, it took no time to do, now when I was testing it anyways 😊 
Your code works perfectly and looks clean, thank you!

**Comment by PolygonHJ** [comment]
This issue seems to have reappeared in the docker versions (tested on Docker version 2 and latest as of 2022/03/28) MariaDB docker version 10.5 - as recommended by the example docker compose file.

(p.s. incredible work and amazing application)

**Pull request merged**
