### PR TITLE
Fixes viktorstrate/photoview#6 : Added "Show favorites" toggle to view the favorited media

### PR DESCRIPTION
**Pull request by stz184**
I have added a "Show only the favorites" checkbox on both /pages and /album/:id/ pages
- On Photos page, when the toggle is checked only albums containing favorited media are displayed and only favorited media is lisred. The URL changes to /photos/favorites and it can be used to directly access the favorited media.
- On the individual album's page, the toggle shows only favorited media when it is checked. The URL changes to /album/ID/favorites and it can be used to directly access the favorited media from this particular album.
- forceVisible() is called when the loading ends in PhotoGallery component because otherwise if you switch to Favorites and some of the favorited images have been outside the viewport before that, they will not be lazy-loaded once they are "moved" to the visible area because non-favorited images are cleared.

### CODE REVIEW

**Comment by viktorstrate** [comment]
Awesome looks great. I will take a proper look and merge, one of the next days. 👍

**Comment by viktorstrate** [comment]
Please make sure your branch is up to date with the `viktorstrate:master` branch.
Try to rebase against my master.

Also in the future, please make a dedicated branch for the pull-request, just for tidiness. 😉

**Comment by stz184** [comment]
Damn, I was so excited to create a pull request, so I completely forgot I am working in the master branch...  (face palm multiple times)
Let me correct this mess...

**Comment by viktorstrate** [comment]
Haha, no worries 😂

**Pull request closed without merging**
