### PR TITLE
Database connection not closed if issue with migration

### PR DESCRIPTION
**Pull request by BkSouX**
Defer is not executed with a fatal, the app crashes directly.
It is better to use a panic, defer is called before exiting the app.

### CODE REVIEW

**Comment by viktorstrate** [comment]
Would it be worse to just manually close the database connection before calling log.Fatal instead?
I think that would be simpler and easier to understand.

Maybe we should handle the case where the [http.ListenAndServe](https://github.com/viktorstrate/photoview/blob/11ea1c13bd0b74953fac55b79ac5a3ea403322a4/api/server.go#L99) fails as well?

**Comment by viktorstrate** [comment]
There is potentially one more place where the database would not be closed properly, and that is if a connection was successful, but the ping failed.

https://github.com/viktorstrate/photoview/blob/master/api/database/mysql.go#L69

**Comment by viktorstrate** [comment]
Awesome I will take a look later 👍

**Comment by viktorstrate** [comment]
The code looks good. I've added some small cleanup changes i found while reading the code.
If it's ok with you, I will merge.

**Comment by BkSouX** [comment]
OK :+1:

**Pull request merged**
